/* 부서테이블 dml */
--회원추가
INSERT INTO USERS VALUES('TEST01','01','TESTNAME01','M',SYSDATE);
INSERT INTO USERS VALUES('TEST02','02','TESTNAME02','F',SYSDATE);
INSERT INTO USERS VALUES('TEST03','03','TESTNAME03','F',SYSDATE);
INSERT INTO USERS VALUES('TEST04','04','TESTNAME04','M',SYSDATE);


--특정 유저 상세조회
SELECT * FROM USERS WHERE USER_ID='TEST01';
--부서 전체 조회
SELECT * FROM USERS;
--회원 비밀번호 변경
UPDATE USERS SET USER_PWD='변경된 비밀번호' WHERE USER_ID='TEST01';
--특정회원 삭제
DELETE FROM USERS FROM USER_ID='TEST02';
